name: 'cleaning_warehouse'
version: '1.0.0'
config-version: 2

profile: 'cleaning_warehouse'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  cleaning_warehouse:
    staging:
      +materialized: view
    facts:
      +materialized: table

